#!/bin/bash

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
SCRIPT_COMMAND="$0"
set -o nounset
set -o pipefail
set -o errexit
trap 'echo "$SCRIPT_COMMAND: error $? at line $LINENO"' ERR

if [[ "$#" = 1 && "$1" = "-q" ]] ; then
    GEN_SCRIPT_CMD="$SCRIPT_DIR/../gen-scripts.py -q" 
elif [[ "$#" = 0 ]] ; then
    GEN_SCRIPT_CMD="$SCRIPT_DIR/../gen-scripts.py"
else
    echo "Only argument supported is -q to enqueue."
    exit 1
fi

# TODO: check SIMPLE_BARRIER = 1 in stamp common/Defines.common.mk

# to change this (or anything else) one has to change the config.py files too
OUTPUT_DIR="$(realpath "$SCRIPT_DIR/../../../results/teaser/")"

[ -e "$OUTPUT_DIR" ] && {
    echo "Output directory «$OUTPUT_DIR» already exists."
    exit 1;
}

# gen-scripts does weird things if the current directory is not right
cd "$SCRIPT_DIR/.."

[ -e "config.py" ] && {
    mv "config.py" "config.py.bak"
    echo $'\e[31m'"Warning"$'\e[0m'": Current «gem5_path/scripts/config.py» moved to «gem5_path/scripts/config.py.bak»."
}

# simulations with 1 thread, locks
cp "$SCRIPT_DIR/config-1.py" "config.py" # Note that gen-scripts does not work if config.py is a symbolic link 
$GEN_SCRIPT_CMD

# simulations with 1 thread
cp "$SCRIPT_DIR/config-2.py" "config.py" # Note that gen-scripts does not work if config.py is a symbolic link 
$GEN_SCRIPT_CMD

# simulations with 16 threads
cp "$SCRIPT_DIR/config-3.py" "config.py" # Note that gen-scripts does not work if config.py is a symbolic link 
$GEN_SCRIPT_CMD

rm "$SCRIPT_DIR/../config.py"

cd "$OUTPUT_DIR"

# Find the output directory name chosen by gen-scripts, which literally depends on the day that the script is run…
GS_OUT_PREFIX="$(cd all/1/ ; echo *_27)"

mkdir -p per_plot/{1..8}

# locks no htm (cfg0\_locks) VS HTM base (htm.cfg1_base)
ln -s "../../all/1/$GS_OUT_PREFIX/XXX" per_plot/1/cfg0_locks
ln -s "../../all/1/$GS_OUT_PREFIX/XXX" per_plot/1/cfg1_base
# TODO: …
